SELECT USER
FROM DUAL;
--==>> HTEST

CREATE OR REPLACE VIEW ASKVIEW
AS
SELECT A.ASK_CODE AS ASK_CODE
     , A.ASK_CATE_CODE AS ASK_CATE_CODE
     , AL.ASK_CATE_CONTENT AS ASK_CATE_CONTENT
     , A.SID_CODE AS SID_CODE
     , TO_CHAR(A.ASK_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ASK_DATE
     , A.ASK_TITLE AS ASK_TITLE
     , A.ASK_CONTENT AS ASK_CONTENT
     , A.ASK_PHOTO AS ASK_PHOTO
     , A.ASK_STATE_CODE AS ASK_STATE_CODE
     , AST.ASK_STATE_CONTENT AS ASK_STATE_CONTENT
     , TO_CHAR(A.ASK_READ, 'YYYY-MM-DD HH24:MI:SS') AS ASK_READ
FROM TBL_ASK A
LEFT OUTER JOIN TBL_ASK_LEG AL
ON A.ASK_CATE_CODE = AL.ASK_CATE_CODE
LEFT OUTER JOIN TBL_ASK_STATE AST
ON A.ASK_STATE_CODE = AST.ASK_STATE_CODE
ORDER BY ASK_CODE
;

SELECT *
FROM ASKVIEW;


COMMIT;
