--21.07.06 아별 추가 작성 (문의글 작성자 닉네임 추가)

SELECT USER
FROM DUAL;
--==>> HTEST

CREATE OR REPLACE VIEW ASKVIEW
AS
SELECT A.ASK_CODE AS ASK_CODE
     , A.ASK_CATE_CODE AS ASK_CATE_CODE
     , AL.ASK_CATE_CONTENT AS ASK_CATE_CONTENT
     , A.SID_CODE AS SID_CODE
     , TO_CHAR(A.ASK_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ASK_DATE
     , A.ASK_TITLE AS ASK_TITLE
     , A.ASK_CONTENT AS ASK_CONTENT
     , A.ASK_PHOTO AS ASK_PHOTO
     , A.ASK_STATE_CODE AS ASK_STATE_CODE
     , AST.ASK_STATE_CONTENT AS ASK_STATE_CONTENT
     , TO_CHAR(A.ASK_READ, 'YYYY-MM-DD HH24:MI:SS') AS ASK_READ
FROM TBL_ASK A
LEFT OUTER JOIN TBL_ASK_LEG AL
ON A.ASK_CATE_CODE = AL.ASK_CATE_CODE
LEFT OUTER JOIN TBL_ASK_STATE AST
ON A.ASK_STATE_CODE = AST.ASK_STATE_CODE
ORDER BY ASK_CODE
;

SELECT *
FROM ASKVIEW;


COMMIT;

--------------------------------------------------------------------------------

--21.07.06 아별 추가 작성

-- 수정 전 데이터 조회
SELECT *
FROM ASKVIEW;
--==>>
/*
1	1	산책메이트	SID003	2021-06-23 00:00:00	강아지가요	강아지가 다른 강아지를 무서워하면 산책이 가능한가요?		2	답변완료	2021-06-23 00:00:00
2	2	다이어리	SID001	2021-06-23 00:00:00	다이어리삭제	다이어리 삭제 시 복구가 불가능한가요??		2	답변완료	2021-06-23 00:00:00
3	2	다이어리	SID001	2021-06-27 00:00:00	다이어리 중복	다이어리 중복 작성하면 어케되나여?		1	미처리	
*/

CREATE OR REPLACE VIEW ASKVIEW
AS
SELECT A.ASK_CODE AS ASK_CODE
     , A.ASK_CATE_CODE AS ASK_CATE_CODE
     , AL.ASK_CATE_CONTENT AS ASK_CATE_CONTENT
     , A.SID_CODE AS SID_CODE
     , M.MEM_NICKNAME AS MEM_NICKNAME
     , TO_CHAR(A.ASK_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ASK_DATE
     , A.ASK_TITLE AS ASK_TITLE
     , A.ASK_CONTENT AS ASK_CONTENT
     , A.ASK_PHOTO AS ASK_PHOTO
     , A.ASK_STATE_CODE AS ASK_STATE_CODE
     , AST.ASK_STATE_CONTENT AS ASK_STATE_CONTENT
     , TO_CHAR(A.ASK_READ, 'YYYY-MM-DD HH24:MI:SS') AS ASK_READ
FROM TBL_ASK A
LEFT OUTER JOIN TBL_ASK_LEG AL
ON A.ASK_CATE_CODE = AL.ASK_CATE_CODE
LEFT OUTER JOIN TBL_ASK_STATE AST
ON A.ASK_STATE_CODE = AST.ASK_STATE_CODE
LEFT OUTER JOIN TBL_SID S
ON A.SID_CODE = S.SID_CODE
LEFT OUTER JOIN TBL_MEMBER M
ON S.MEM_CODE = M.MEM_CODE
ORDER BY ASK_CODE;


