SELECT *
FROM TBL_MEMBER
ORDER BY 1;

SELECT *
FROM TBL_ADMIN;

SELECT *
FROM TBL_SID;

-- 익스포트 때문에 잘못된 회원 비밀번호 업데이트
UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('1224', 'joohee')
WHERE MEM_CODE='MEM001';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('1102', 'hyeyeon')
WHERE MEM_CODE='MEM002';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('1022', 'harim')
WHERE MEM_CODE='MEM003';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('1006', 'hyerim')
WHERE MEM_CODE='MEM006';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('0118', 'dongwon')
WHERE MEM_CODE='MEM007';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('1012', 'kangjun')
WHERE MEM_CODE='MEM008';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('0126', 'moonbin')
WHERE MEM_CODE='MEM009';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('0330', 'eunwoo')
WHERE MEM_CODE='MEM010';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('1105', 'ttutto')
WHERE MEM_CODE='MEM13';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('0121', 'dowl')
WHERE MEM_CODE='MEM14';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('0115', 'heyitsme')
WHERE MEM_CODE='MEM15';

UPDATE TBL_MEMBER
SET MEM_PW=CRYPTPACK.ENCRYPT('0719', 'notSongGang')
WHERE MEM_CODE='MEM16';
--==>> 1 행 이(가) 업데이트되었습니다. * 12

-- 익스포트 때문에 잘못된 관리자 비밀번호 업데이트
UPDATE TBL_ADMIN
SET ADMIN_PW = CRYPTPACK.ENCRYPT('0308', 'admin1')
WHERE ADMIN_CODE = 'ADM001';

UPDATE TBL_ADMIN
SET ADMIN_PW = CRYPTPACK.ENCRYPT('0909', 'admin2')
WHERE ADMIN_CODE = 'ADM002';
--==>> 1 행 이(가) 업데이트되었습니다. * 2

COMMIT;