SELECT USER
FROM DUAL;
--==>> HTEST


CREATE OR REPLACE VIEW BOARDVIEW
AS
SELECT N.NOTICE_CODE AS NUM
     , N.NOTICE_WRITER AS WRITER
     , N.NOTICE_HEAD_CODE AS HEAD_CODE
     , N.NOTICE_TITLE AS TITLE
     , N.NOTICE_CONTENT AS CONTENT
     , N.NOTICE_PHOTO AS PHOTO
     , N.NOTICE_VIEW AS VIEWNUM
     , N.NOTICE_LIKE AS LIKENUM
     , TO_CHAR(N.NOTICE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CONTENT_DATE
     , (SELECT NOTICE_CATE_CONTENT
        FROM TBL_NOTICE_LEG
        WHERE NOTICE_CATE_CODE = N.NOTICE_HEAD_CODE) AS CATE_CONTENT
FROM TBL_NOTICE N
UNION ALL
SELECT B.BOARD_CODE AS BOARD_CODE
     , B.BOARD_WRITER AS BOARD_WRITER
     , B.BOARD_CATE_CODE AS BOARD_CATE_CODE
     , B.BOARD_TITLE AS BOARD_TITLE
     , B.BOARD_CONTENT AS BOARD_CONTENT
     , B.BOARD_PHOTO AS BOARD_PHOTO
     , B.BOARD_VIEW AS BOARD_VIEW
     , B.BOARD_LIKE AS BOARD_LIKE
     , TO_CHAR(B.BOARD_DATE, 'YYYY-MM-DD HH24:MI:SS') AS BOARD_DATE
     , (SELECT BOARD_CATE_CONTENT
        FROM TBL_BOARD_LEG
        WHERE BOARD_CATE_CODE = B.BOARD_CATE_CODE) AS BOARD_CATE_CONTENT
FROM TBL_BOARD B;

SELECT *
FROM BOARDVIEW;

SELECT *
FROM TBL_NOTICE;
/*
NOTICE_CODE	NOTICE_WRITER	NOTICE_HEAD_CODE	NOTICE_TITLE	NOTICE_PHOTO	NOTICE_CONTENT	NOTICE_VIEW	NOTICE_LIKE	NOTICE_DATE
1	ADM001	2	강아지배변봉투		산책 시 강아지 배변봉투를 꼭 챙겨주세요	0	0	21/06/26
*/

SELECT *
FROM TBL_NOTICE_LEG;

SELECT *
FROM TBL_BOARD_LEG;


SELECT *
FROM TBL_BOARD;
/*
BOARD_CODE	BOARD_WRITER	BOARD_CATE_CODE	BOARD_TITLE	BOARD_CONTENT	BOARD_PHOTO	BOARD_VIEW	BOARD_LIKE
1	SID002	3	오늘대박	오늘 산책메이트 산책갔는데 옆집 사람이었다 문열때부터 같이갔음 대박		0	0
*/

COMMIT;