select *
from TBL_BOARD_COMMENT
;

SELECT *
FROM TBL_BOARD;

SELECT *
FROM BOARDVIEW;

CREATE OR REPLACE VIEW BOARDCOMMVIEW
AS
SELECT B.BOARD_WRITER
     , BC.BOARD_COMM_CODE
     , BC.BOARD_CODE
     , BC.BOARD_COMM_WRITER
     , BC.BOARD_COMM_CONTENT
     , BC.BOARD_COMM_DATE
FROM TBL_BOARD_COMMENT BC 
LEFT OUTER JOIN TBL_BOARD B
ON BC.BOARD_CODE = B.BOARD_CODE
ORDER BY BC.BOARD_COMM_CODE
;

SELECT *
FROM BOARDCOMMVIEW;