SELECT USER
FROM DUAL;
--==>> HAROOTPUPPY

SELECT *
FROM TBL_DAILY;


-- 1번 조회
SELECT C.COMMON_CODE AS COMMON_CODE
     , TO_CHAR(C.COMMON_START, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_START
     , TO_CHAR(C.COMMON_END, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_END
     , C.COMMON_MEMO AS COMMON_MEMO
     , C.COMMON_PHOTO AS COMMON_PHOTO
     , D.DAILY_CODE AS DAILY_CODE
     , D.RELATION_CODE AS RELATION_CODE
     --, R.SID_CODE AS SID_CODE
     --, R.PET_CODE AS PET_CODE
     , TO_CHAR(D.DAILY_DATE, 'YYYY-MM-DD') AS DAILY_DATE
     , S.STATE_CODE AS STATE_CODE
     , WEI.WEIGHT_CODE AS WEIGHT_CODE
     , WEI.WEIGHT AS WEIGHT
     , M.MEAL_CODE AS MEAL_CODE
     , MI.MEAL_NAME AS MEAL_NAME
     , MI.MEAL_AMOUNT AS MEAL_AMOUNT
     , MI.UNIT_CODE AS MEAL_UNIT_CODE
     --, U.UNIT_CONTENT AS UNIT_CONTENT
     , M.MEAL_INFO_CODE AS MEAL_INFO_CODE
     , SN.SNACK_CODE AS SNACK_CODE
     , SNI.SNACK_INFO_CODE AS SNACK_INFO_CODE
     , SNI.SNACK_NAME AS SNACK_NAME
     , SNI.SNACK_AMOUNT AS SNACK_AMOUNT
     , W.WALK_CODE AS WALK_CODE
     , T.TOOTH_CODE AS TOOTH_CODE
     , E.EAR_CODE AS EAR_CODE
     , B.BATH_CODE AS BATH_CODE
     , CHK.CHECK_CODE AS CHECK_CODE
     , CHK.HOSPITAL_CODE AS CHK_HOSPITAL_CODE
     , CHK.CHECK_COST AS CHECK_COST
     , TO_CHAR(CHK.CHECK_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS CHECK_NEXT
     , IJ.INJECT_CODE AS INJECT_CODE
     , IJ.HOSPITAL_CODE AS IJ_HOSPITAL_CODE
     , IJT.INJECT_TYPE_CODE AS INJECT_TYPE_CODE
     , IJT.INJECT_TYPE_NAME AS INJECT_TYPE_NAME
     , IJ.INJECT_COST AS INJECT_COST
     , TO_CHAR(IJ.INJECT_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS INJECT_NEXT
     , IL.ILLNESS_CODE AS ILLNESS_CODE
     , IL.HOSPITAL_CODE AS IL_HOSPITAL_CODE
     , IL.ILLNESS_NAME AS ILLNESS_NAME
     , IL.ILLNESS_COST AS ILLNESS_COST
     , TO_CHAR(IL.ILLNESS_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS ILLNESS_NEXT
     , SUR.SURGERY_CODE AS SURGERY_CODE
     , SUR.HOSPITAL_CODE AS SUR_HOSPITAL_CODE
     , SUR.SURGERY_NAME AS SURGERY_NAME
     , SUR.SURGERY_COST AS SURGERY_COST
     , TO_CHAR(SUR.SURGERY_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS SURGERY_NEXT
     , BT.BEAUTY_CODE AS BEAUTY_CODE
     , BT.BEAUTY_COST AS BEAUTY_COST
     , SH.SHOP_CODE AS SHOP_CODE
     , SH.SHOP_NAME AS SHOP_NAME
     , BTT.BEAUTY_TYPE_CODE AS BEAUTY_TYPE_CODE
     , BTT.BEAUTY_TYPE_NAME AS BEAUTY_TYPE_NAME
     , NUT.NUT_CODE AS NUT_CODE
     , NUTI.NUT_INFO_CODE AS NUT_INFO_CODE
     , NUTI.NUT_NAME AS NUT_NAME
     , NUTI.NUT_AMOUNT AS NUT_AMOUNT
     , NUTI.UNIT_CODE AS NUTI_UNIT_CODE
     , TR.TRAIN_CODE AS TRAIN_CODE
     , TR.TRAIN_NAME AS TRAIN_NAME
     , TRT.TRAIN_TYPE_CODE AS TRAIN_TYPE_CODE
     , TRT.TRAIN_TYPE_CONTENT AS TRAIN_TYPE_NAME
     , ETC.ETC_CODE AS ETC_CODE
     , ETC.ETC_TITLE AS ETC_TITLE
     , ETC.ETC_CONTENT AS ETC_CONTENT
     , TOI.TOILET_CODE AS TOILET_CODE
     , UR.URINE_CODE AS URINE_CODE
     , UR.URINE_STATE AS URINE_STATE
     , UR.URINE_ETC AS URINE_ETC
     , FC.FECES_CODE AS FECES_CODE
     , FC.FECES_STATE AS FECES_STATE
     , FC.FECES_ETC AS FECES_ETC
     , MED.MEDICINE_CODE AS MEDICINE_CODE
     , MEDI.MEDICINE_INFO_CODE AS MEDICINE_INFO_CODE
     , MEDI.MEDICINE_NAME AS MEDICINE_NAME
     , MEDI.MEDICINE_EFFECT AS MEDICINE_EFFECT
     , MEDI.MEDICINE_AMOUNT AS MEDICINE_AMOUNT
     , MEDI.UNIT_CODE AS MEDI_UNIT_CODE
     , MEDI.MEDICINE_DISEASE AS MEDICINE_DISEASE
     , BR.BIRTH_CODE AS BIRTH_CODE
     , BR.BIRTH_TEMPERATURE AS BIRTH_TEMPERATURE
     , BR.BIRTH_ACCOUNT AS BIRTH_ACCOUNT
FROM TBL_COMMON C, TBL_DAILY D, TBL_RELATION R
   , TBL_STATE S, TBL_STATE_LEG SL
   , TBL_WEIGHT WEI
   , TBL_MEAL M, TBL_MEAL_INFO MI, TBL_MEAL_TYPE MT--, TBL_UNIT U
   , TBL_SNACK SN, TBL_SNACK_INFO SNI, TBL_SNACK_TYPE SNT
   , TBL_WALK W, TBL_TOOTH T, TBL_EAR E, TBL_BATH B
   , TBL_CHECK CHK, TBL_INJECT IJ, TBL_ILLNESS IL, TBL_SURGERY SUR, TBL_INJECT_TYPE IJT
   , TBL_BEAUTY BT, TBL_SHOP SH, TBL_BEAUTY_TYPE BTT
   , TBL_NUTRIENTS NUT, TBL_NUTRIENTS_INFO NUTI
   , TBL_TRAIN TR, TBL_TRAIN_TYPE TRT
   , TBL_ETC ETC
   , TBL_TOILET TOI, TBL_URINE UR, TBL_FECES FC
   , TBL_MEDICINE MED, TBL_MEDICINE_INFO MEDI
   , TBL_BIRTH BR
WHERE C.DAILY_CODE(+) = D.DAILY_CODE
  AND D.RELATION_CODE = R.RELATION_CODE(+)
  AND C.COMMON_CODE = S.COMMON_CODE(+)
  AND S.STATE_LEG_CODE = SL.STATE_LEG_CODE(+)
  AND C.COMMON_CODE = WEI.COMMON_CODE(+)
  AND C.COMMON_CODE = M.COMMON_CODE(+)
  AND M.MEAL_INFO_CODE = MI.MEAL_INFO_CODE(+)
  AND MI.MEAL_TYPE = MT.MEAL_TYPE_CODE(+)
  --AND MI.UNIT_CODE = U.UNIT_CODE(+)
  AND C.COMMON_CODE = SN.COMMON_CODE(+)
  AND SN.SNACK_INFO_CODE = SNI.SNACK_INFO_CODE(+)
  AND SNI.SNACK_TYPE = SNT.SNACK_TYPE_CODE(+)
  AND C.COMMON_CODE = W.COMMON_CODE(+)
  AND C.COMMON_CODE = T.COMMON_CODE(+)
  AND C.COMMON_CODE = E.COMMON_CODE(+)
  AND C.COMMON_CODE = B.COMMON_CODE(+)
  AND C.COMMON_CODE = CHK.COMMON_CODE(+)
  AND C.COMMON_CODE = IJ.COMMON_CODE(+)
  AND C.COMMON_CODE = IL.COMMON_CODE(+)
  AND C.COMMON_CODE = SUR.COMMON_CODE(+)
  AND IJ.INJECT_TYPE_CODE = IJT.INJECT_TYPE_CODE(+)
  AND C.COMMON_CODE = BT.COMMON_CODE(+)
  AND BT.SHOP_CODE = SH.SHOP_CODE(+)
  AND BT.BEAUTY_TYPE_CODE = BTT.BEAUTY_TYPE_CODE(+)
  AND C.COMMON_CODE = NUT.COMMON_CODE(+)
  --AND NUT.MEDICINE_TYPE_CODE = MDT.MEDICINE_TYPE_CODE(+)
  AND NUT.NUT_INFO_CODE = NUTI.NUT_INFO_CODE(+)
  AND C.COMMON_CODE = TR.COMMON_CODE(+)
  AND TR.TRAIN_TYPE = TRT.TRAIN_TYPE_CODE(+)
  AND C.COMMON_CODE = ETC.COMMON_CODE(+)
  AND C.COMMON_CODE = TOI.COMMON_CODE(+)
  AND TOI.URINE_CODE = UR.URINE_CODE(+)
  AND TOI.FECES_CODE = FC.FECES_CODE(+)
  AND C.COMMON_CODE = MED.COMMON_CODE(+)
  AND MED.MEDICINE_INFO_CODE = MEDI.MEDICINE_INFO_CODE(+)
  AND C.COMMON_CODE = BR.COMMON_CODE(+)
ORDER BY COMMON_CODE;





-- 1번 뷰 생성
CREATE OR REPLACE VIEW DIARYVIEW
AS
SELECT C.COMMON_CODE AS COMMON_CODE
     , TO_CHAR(C.COMMON_START, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_START
     , TO_CHAR(C.COMMON_END, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_END
     , C.COMMON_MEMO AS COMMON_MEMO
     , C.COMMON_PHOTO AS COMMON_PHOTO
     , D.DAILY_CODE AS DAILY_CODE
     , D.RELATION_CODE AS RELATION_CODE
     --, R.SID_CODE AS SID_CODE
     --, R.PET_CODE AS PET_CODE
     , TO_CHAR(D.DAILY_DATE, 'YYYY-MM-DD') AS DAILY_DATE
     , S.STATE_CODE AS STATE_CODE
     , WEI.WEIGHT_CODE AS WEIGHT_CODE
     , WEI.WEIGHT AS WEIGHT
     , M.MEAL_CODE AS MEAL_CODE
     , MI.MEAL_NAME AS MEAL_NAME
     , MI.MEAL_AMOUNT AS MEAL_AMOUNT
     , MI.UNIT_CODE AS MEAL_UNIT_CODE
     --, U.UNIT_CONTENT AS UNIT_CONTENT
     , M.MEAL_INFO_CODE AS MEAL_INFO_CODE
     , SN.SNACK_CODE AS SNACK_CODE
     , SNI.SNACK_INFO_CODE AS SNACK_INFO_CODE
     , SNI.SNACK_NAME AS SNACK_NAME
     , SNI.SNACK_AMOUNT AS SNACK_AMOUNT
     , W.WALK_CODE AS WALK_CODE
     , T.TOOTH_CODE AS TOOTH_CODE
     , E.EAR_CODE AS EAR_CODE
     , B.BATH_CODE AS BATH_CODE
     , CHK.CHECK_CODE AS CHECK_CODE
     , CHK.HOSPITAL_CODE AS CHK_HOSPITAL_CODE
     , CHK.CHECK_COST AS CHECK_COST
     , TO_CHAR(CHK.CHECK_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS CHECK_NEXT
     , IJ.INJECT_CODE AS INJECT_CODE
     , IJ.HOSPITAL_CODE AS IJ_HOSPITAL_CODE
     , IJT.INJECT_TYPE_CODE AS INJECT_TYPE_CODE
     , IJT.INJECT_TYPE_NAME AS INJECT_TYPE_NAME
     , IJ.INJECT_COST AS INJECT_COST
     , TO_CHAR(IJ.INJECT_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS INJECT_NEXT
     , IL.ILLNESS_CODE AS ILLNESS_CODE
     , IL.HOSPITAL_CODE AS IL_HOSPITAL_CODE
     , IL.ILLNESS_NAME AS ILLNESS_NAME
     , IL.ILLNESS_COST AS ILLNESS_COST
     , TO_CHAR(IL.ILLNESS_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS ILLNESS_NEXT
     , SUR.SURGERY_CODE AS SURGERY_CODE
     , SUR.HOSPITAL_CODE AS SUR_HOSPITAL_CODE
     , SUR.SURGERY_NAME AS SURGERY_NAME
     , SUR.SURGERY_COST AS SURGERY_COST
     , TO_CHAR(SUR.SURGERY_NEXT, 'YYYY-MM-DD HH24:MI:SS') AS SURGERY_NEXT
     , BT.BEAUTY_CODE AS BEAUTY_CODE
     , BT.BEAUTY_COST AS BEAUTY_COST
     , SH.SHOP_CODE AS SHOP_CODE
     , SH.SHOP_NAME AS SHOP_NAME
     , BTT.BEAUTY_TYPE_CODE AS BEAUTY_TYPE_CODE
     , BTT.BEAUTY_TYPE_NAME AS BEAUTY_TYPE_NAME
     , NUT.NUT_CODE AS NUT_CODE
     , NUTI.NUT_INFO_CODE AS NUT_INFO_CODE
     , NUTI.NUT_NAME AS NUT_NAME
     , NUTI.NUT_AMOUNT AS NUT_AMOUNT
     , NUTI.UNIT_CODE AS NUTI_UNIT_CODE
     , TR.TRAIN_CODE AS TRAIN_CODE
     , TR.TRAIN_NAME AS TRAIN_NAME
     , TRT.TRAIN_TYPE_CODE AS TRAIN_TYPE_CODE
     , TRT.TRAIN_TYPE_CONTENT AS TRAIN_TYPE_NAME
     , ETC.ETC_CODE AS ETC_CODE
     , ETC.ETC_TITLE AS ETC_TITLE
     , ETC.ETC_CONTENT AS ETC_CONTENT
     , TOI.TOILET_CODE AS TOILET_CODE
     , UR.URINE_CODE AS URINE_CODE
     , UR.URINE_STATE AS URINE_STATE
     , UR.URINE_ETC AS URINE_ETC
     , FC.FECES_CODE AS FECES_CODE
     , FC.FECES_STATE AS FECES_STATE
     , FC.FECES_ETC AS FECES_ETC
     , MED.MEDICINE_CODE AS MEDICINE_CODE
     , MEDI.MEDICINE_INFO_CODE AS MEDICINE_INFO_CODE
     , MEDI.MEDICINE_NAME AS MEDICINE_NAME
     , MEDI.MEDICINE_EFFECT AS MEDICINE_EFFECT
     , MEDI.MEDICINE_AMOUNT AS MEDICINE_AMOUNT
     , MEDI.UNIT_CODE AS MEDI_UNIT_CODE
     , MEDI.MEDICINE_DISEASE AS MEDICINE_DISEASE
     , BR.BIRTH_CODE AS BIRTH_CODE
     , BR.BIRTH_TEMPERATURE AS BIRTH_TEMPERATURE
     , BR.BIRTH_ACCOUNT AS BIRTH_ACCOUNT
FROM TBL_COMMON C, TBL_DAILY D, TBL_RELATION R
   , TBL_STATE S, TBL_STATE_LEG SL
   , TBL_WEIGHT WEI
   , TBL_MEAL M, TBL_MEAL_INFO MI, TBL_MEAL_TYPE MT--, TBL_UNIT U
   , TBL_SNACK SN, TBL_SNACK_INFO SNI, TBL_SNACK_TYPE SNT
   , TBL_WALK W, TBL_TOOTH T, TBL_EAR E, TBL_BATH B
   , TBL_CHECK CHK, TBL_INJECT IJ, TBL_ILLNESS IL, TBL_SURGERY SUR, TBL_INJECT_TYPE IJT
   , TBL_BEAUTY BT, TBL_SHOP SH, TBL_BEAUTY_TYPE BTT
   , TBL_NUTRIENTS NUT, TBL_NUTRIENTS_INFO NUTI
   , TBL_TRAIN TR, TBL_TRAIN_TYPE TRT
   , TBL_ETC ETC
   , TBL_TOILET TOI, TBL_URINE UR, TBL_FECES FC
   , TBL_MEDICINE MED, TBL_MEDICINE_INFO MEDI
   , TBL_BIRTH BR
WHERE C.DAILY_CODE(+) = D.DAILY_CODE
  AND D.RELATION_CODE = R.RELATION_CODE(+)
  AND C.COMMON_CODE = S.COMMON_CODE(+)
  AND S.STATE_LEG_CODE = SL.STATE_LEG_CODE(+)
  AND C.COMMON_CODE = WEI.COMMON_CODE(+)
  AND C.COMMON_CODE = M.COMMON_CODE(+)
  AND M.MEAL_INFO_CODE = MI.MEAL_INFO_CODE(+)
  AND MI.MEAL_TYPE = MT.MEAL_TYPE_CODE(+)
  --AND MI.UNIT_CODE = U.UNIT_CODE(+)
  AND C.COMMON_CODE = SN.COMMON_CODE(+)
  AND SN.SNACK_INFO_CODE = SNI.SNACK_INFO_CODE(+)
  AND SNI.SNACK_TYPE = SNT.SNACK_TYPE_CODE(+)
  AND C.COMMON_CODE = W.COMMON_CODE(+)
  AND C.COMMON_CODE = T.COMMON_CODE(+)
  AND C.COMMON_CODE = E.COMMON_CODE(+)
  AND C.COMMON_CODE = B.COMMON_CODE(+)
  AND C.COMMON_CODE = CHK.COMMON_CODE(+)
  AND C.COMMON_CODE = IJ.COMMON_CODE(+)
  AND C.COMMON_CODE = IL.COMMON_CODE(+)
  AND C.COMMON_CODE = SUR.COMMON_CODE(+)
  AND IJ.INJECT_TYPE_CODE = IJT.INJECT_TYPE_CODE(+)
  AND C.COMMON_CODE = BT.COMMON_CODE(+)
  AND BT.SHOP_CODE = SH.SHOP_CODE(+)
  AND BT.BEAUTY_TYPE_CODE = BTT.BEAUTY_TYPE_CODE(+)
  AND C.COMMON_CODE = NUT.COMMON_CODE(+)
  --AND NUT.MEDICINE_TYPE_CODE = MDT.MEDICINE_TYPE_CODE(+)
  AND NUT.NUT_INFO_CODE = NUTI.NUT_INFO_CODE(+)
  AND C.COMMON_CODE = TR.COMMON_CODE(+)
  AND TR.TRAIN_TYPE = TRT.TRAIN_TYPE_CODE(+)
  AND C.COMMON_CODE = ETC.COMMON_CODE(+)
  AND C.COMMON_CODE = TOI.COMMON_CODE(+)
  AND TOI.URINE_CODE = UR.URINE_CODE(+)
  AND TOI.FECES_CODE = FC.FECES_CODE(+)
  AND C.COMMON_CODE = MED.COMMON_CODE(+)
  AND MED.MEDICINE_INFO_CODE = MEDI.MEDICINE_INFO_CODE(+)
  AND C.COMMON_CODE = BR.COMMON_CODE(+)
ORDER BY COMMON_CODE;
--==>> View DIARYVIEW이(가) 생성되었습니다.

																																																																					



-- 2번 조회(코드들만 가져옴)
SELECT C.COMMON_CODE AS COMMON_CODE
     , TO_CHAR(C.COMMON_START, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_START
     , TO_CHAR(C.COMMON_END, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_END
     , D.DAILY_CODE AS DAILY_CODE
     , D.RELATION_CODE AS RELATION_CODE
     , TO_CHAR(D.DAILY_DATE, 'YYYY-MM-DD') AS DAILY_DATE
     , S.STATE_CODE AS STATE_CODE
     , WEI.WEIGHT_CODE AS WEIGHT_CODE
     , M.MEAL_CODE AS MEAL_CODE
     , MI.UNIT_CODE AS MEAL_UNIT_CODE
     , M.MEAL_INFO_CODE AS MEAL_INFO_CODE
     , SN.SNACK_CODE AS SNACK_CODE
     , SNI.SNACK_INFO_CODE AS SNACK_INFO_CODE
     , W.WALK_CODE AS WALK_CODE
     , T.TOOTH_CODE AS TOOTH_CODE
     , E.EAR_CODE AS EAR_CODE
     , B.BATH_CODE AS BATH_CODE
     , CHK.CHECK_CODE AS CHECK_CODE
     , CHK.HOSPITAL_CODE AS CHK_HOSPITAL_CODE
     , IJ.INJECT_CODE AS INJECT_CODE
     , IJ.HOSPITAL_CODE AS IJ_HOSPITAL_CODE
     , IJT.INJECT_TYPE_CODE AS INJECT_TYPE_CODE
     , IL.ILLNESS_CODE AS ILLNESS_CODE
     , IL.HOSPITAL_CODE AS IL_HOSPITAL_CODE
     , SUR.SURGERY_CODE AS SURGERY_CODE
     , SUR.HOSPITAL_CODE AS SUR_HOSPITAL_CODE
     , BT.BEAUTY_CODE AS BEAUTY_CODE
     , SH.SHOP_CODE AS SHOP_CODE
     , BTT.BEAUTY_TYPE_CODE AS BEAUTY_TYPE_CODE
     , NUT.NUT_CODE AS NUT_CODE
     , NUTI.NUT_INFO_CODE AS NUT_INFO_CODE
     , NUTI.UNIT_CODE AS NUTI_UNIT_CODE
     , TR.TRAIN_CODE AS TRAIN_CODE
     , TRT.TRAIN_TYPE_CODE AS TRAIN_TYPE_CODE
     , ETC.ETC_CODE AS ETC_CODE
     , TOI.TOILET_CODE AS TOILET_CODE
     , UR.URINE_CODE AS URINE_CODE
     , FC.FECES_CODE AS FECES_CODE
     , MED.MEDICINE_CODE AS MEDICINE_CODE
     , MEDI.MEDICINE_INFO_CODE AS MEDICINE_INFO_CODE
     , MEDI.UNIT_CODE AS MEDI_UNIT_CODE
     , BR.BIRTH_CODE AS BIRTH_CODE
FROM TBL_COMMON C, TBL_DAILY D, TBL_RELATION R
   , TBL_STATE S, TBL_STATE_LEG SL
   , TBL_WEIGHT WEI
   , TBL_MEAL M, TBL_MEAL_INFO MI, TBL_MEAL_TYPE MT--, TBL_UNIT U
   , TBL_SNACK SN, TBL_SNACK_INFO SNI, TBL_SNACK_TYPE SNT
   , TBL_WALK W, TBL_TOOTH T, TBL_EAR E, TBL_BATH B
   , TBL_CHECK CHK, TBL_INJECT IJ, TBL_ILLNESS IL, TBL_SURGERY SUR, TBL_INJECT_TYPE IJT
   , TBL_BEAUTY BT, TBL_SHOP SH, TBL_BEAUTY_TYPE BTT
   , TBL_NUTRIENTS NUT, TBL_NUTRIENTS_INFO NUTI
   , TBL_TRAIN TR, TBL_TRAIN_TYPE TRT
   , TBL_ETC ETC
   , TBL_TOILET TOI, TBL_URINE UR, TBL_FECES FC
   , TBL_MEDICINE MED, TBL_MEDICINE_INFO MEDI
   , TBL_BIRTH BR
WHERE C.DAILY_CODE(+) = D.DAILY_CODE
  AND D.RELATION_CODE = R.RELATION_CODE(+)
  AND C.COMMON_CODE = S.COMMON_CODE(+)
  AND S.STATE_LEG_CODE = SL.STATE_LEG_CODE(+)
  AND C.COMMON_CODE = WEI.COMMON_CODE(+)
  AND C.COMMON_CODE = M.COMMON_CODE(+)
  AND M.MEAL_INFO_CODE = MI.MEAL_INFO_CODE(+)
  AND MI.MEAL_TYPE = MT.MEAL_TYPE_CODE(+)
  AND C.COMMON_CODE = SN.COMMON_CODE(+)
  AND SN.SNACK_INFO_CODE = SNI.SNACK_INFO_CODE(+)
  AND SNI.SNACK_TYPE = SNT.SNACK_TYPE_CODE(+)
  AND C.COMMON_CODE = W.COMMON_CODE(+)
  AND C.COMMON_CODE = T.COMMON_CODE(+)
  AND C.COMMON_CODE = E.COMMON_CODE(+)
  AND C.COMMON_CODE = B.COMMON_CODE(+)
  AND C.COMMON_CODE = CHK.COMMON_CODE(+)
  AND C.COMMON_CODE = IJ.COMMON_CODE(+)
  AND C.COMMON_CODE = IL.COMMON_CODE(+)
  AND C.COMMON_CODE = SUR.COMMON_CODE(+)
  AND IJ.INJECT_TYPE_CODE = IJT.INJECT_TYPE_CODE(+)
  AND C.COMMON_CODE = BT.COMMON_CODE(+)
  AND BT.SHOP_CODE = SH.SHOP_CODE(+)
  AND BT.BEAUTY_TYPE_CODE = BTT.BEAUTY_TYPE_CODE(+)
  AND C.COMMON_CODE = NUT.COMMON_CODE(+)
  AND NUT.NUT_INFO_CODE = NUTI.NUT_INFO_CODE(+)
  AND C.COMMON_CODE = TR.COMMON_CODE(+)
  AND TR.TRAIN_TYPE = TRT.TRAIN_TYPE_CODE(+)
  AND C.COMMON_CODE = ETC.COMMON_CODE(+)
  AND C.COMMON_CODE = TOI.COMMON_CODE(+)
  AND TOI.URINE_CODE = UR.URINE_CODE(+)
  AND TOI.FECES_CODE = FC.FECES_CODE(+)
  AND C.COMMON_CODE = MED.COMMON_CODE(+)
  AND MED.MEDICINE_INFO_CODE = MEDI.MEDICINE_INFO_CODE(+)
  AND C.COMMON_CODE = BR.COMMON_CODE(+)
ORDER BY COMMON_CODE;





-- 2번 뷰 생성(코드들만 가져옴)
CREATE OR REPLACE VIEW DIARYVIEW
AS
SELECT C.COMMON_CODE AS COMMON_CODE
     , TO_CHAR(C.COMMON_START, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_START
     , TO_CHAR(C.COMMON_END, 'YYYY-MM-DD HH24:MI:SS') AS COMMON_END
     , D.DAILY_CODE AS DAILY_CODE
     , D.RELATION_CODE AS RELATION_CODE
     , TO_CHAR(D.DAILY_DATE, 'YYYY-MM-DD') AS DAILY_DATE
     , S.STATE_CODE AS STATE_CODE
     , WEI.WEIGHT_CODE AS WEIGHT_CODE
     , M.MEAL_CODE AS MEAL_CODE
     , MI.UNIT_CODE AS MEAL_UNIT_CODE
     , M.MEAL_INFO_CODE AS MEAL_INFO_CODE
     , SN.SNACK_CODE AS SNACK_CODE
     , SNI.SNACK_INFO_CODE AS SNACK_INFO_CODE
     , W.WALK_CODE AS WALK_CODE
     , T.TOOTH_CODE AS TOOTH_CODE
     , E.EAR_CODE AS EAR_CODE
     , B.BATH_CODE AS BATH_CODE
     , CHK.CHECK_CODE AS CHECK_CODE
     , CHK.HOSPITAL_CODE AS CHK_HOSPITAL_CODE
     , IJ.INJECT_CODE AS INJECT_CODE
     , IJ.HOSPITAL_CODE AS IJ_HOSPITAL_CODE
     , IJT.INJECT_TYPE_CODE AS INJECT_TYPE_CODE
     , IL.ILLNESS_CODE AS ILLNESS_CODE
     , IL.HOSPITAL_CODE AS IL_HOSPITAL_CODE
     , SUR.SURGERY_CODE AS SURGERY_CODE
     , SUR.HOSPITAL_CODE AS SUR_HOSPITAL_CODE
     , BT.BEAUTY_CODE AS BEAUTY_CODE
     , SH.SHOP_CODE AS SHOP_CODE
     , BTT.BEAUTY_TYPE_CODE AS BEAUTY_TYPE_CODE
     , NUT.NUT_CODE AS NUT_CODE
     , NUTI.NUT_INFO_CODE AS NUT_INFO_CODE
     , NUTI.UNIT_CODE AS NUTI_UNIT_CODE
     , TR.TRAIN_CODE AS TRAIN_CODE
     , TRT.TRAIN_TYPE_CODE AS TRAIN_TYPE_CODE
     , ETC.ETC_CODE AS ETC_CODE
     , TOI.TOILET_CODE AS TOILET_CODE
     , UR.URINE_CODE AS URINE_CODE
     , FC.FECES_CODE AS FECES_CODE
     , MED.MEDICINE_CODE AS MEDICINE_CODE
     , MEDI.MEDICINE_INFO_CODE AS MEDICINE_INFO_CODE
     , MEDI.UNIT_CODE AS MEDI_UNIT_CODE
     , BR.BIRTH_CODE AS BIRTH_CODE
FROM TBL_COMMON C, TBL_DAILY D, TBL_RELATION R
   , TBL_STATE S, TBL_STATE_LEG SL
   , TBL_WEIGHT WEI
   , TBL_MEAL M, TBL_MEAL_INFO MI, TBL_MEAL_TYPE MT--, TBL_UNIT U
   , TBL_SNACK SN, TBL_SNACK_INFO SNI, TBL_SNACK_TYPE SNT
   , TBL_WALK W, TBL_TOOTH T, TBL_EAR E, TBL_BATH B
   , TBL_CHECK CHK, TBL_INJECT IJ, TBL_ILLNESS IL, TBL_SURGERY SUR, TBL_INJECT_TYPE IJT
   , TBL_BEAUTY BT, TBL_SHOP SH, TBL_BEAUTY_TYPE BTT
   , TBL_NUTRIENTS NUT, TBL_NUTRIENTS_INFO NUTI
   , TBL_TRAIN TR, TBL_TRAIN_TYPE TRT
   , TBL_ETC ETC
   , TBL_TOILET TOI, TBL_URINE UR, TBL_FECES FC
   , TBL_MEDICINE MED, TBL_MEDICINE_INFO MEDI
   , TBL_BIRTH BR
WHERE C.DAILY_CODE(+) = D.DAILY_CODE
  AND D.RELATION_CODE = R.RELATION_CODE(+)
  AND C.COMMON_CODE = S.COMMON_CODE(+)
  AND S.STATE_LEG_CODE = SL.STATE_LEG_CODE(+)
  AND C.COMMON_CODE = WEI.COMMON_CODE(+)
  AND C.COMMON_CODE = M.COMMON_CODE(+)
  AND M.MEAL_INFO_CODE = MI.MEAL_INFO_CODE(+)
  AND MI.MEAL_TYPE = MT.MEAL_TYPE_CODE(+)
  AND C.COMMON_CODE = SN.COMMON_CODE(+)
  AND SN.SNACK_INFO_CODE = SNI.SNACK_INFO_CODE(+)
  AND SNI.SNACK_TYPE = SNT.SNACK_TYPE_CODE(+)
  AND C.COMMON_CODE = W.COMMON_CODE(+)
  AND C.COMMON_CODE = T.COMMON_CODE(+)
  AND C.COMMON_CODE = E.COMMON_CODE(+)
  AND C.COMMON_CODE = B.COMMON_CODE(+)
  AND C.COMMON_CODE = CHK.COMMON_CODE(+)
  AND C.COMMON_CODE = IJ.COMMON_CODE(+)
  AND C.COMMON_CODE = IL.COMMON_CODE(+)
  AND C.COMMON_CODE = SUR.COMMON_CODE(+)
  AND IJ.INJECT_TYPE_CODE = IJT.INJECT_TYPE_CODE(+)
  AND C.COMMON_CODE = BT.COMMON_CODE(+)
  AND BT.SHOP_CODE = SH.SHOP_CODE(+)
  AND BT.BEAUTY_TYPE_CODE = BTT.BEAUTY_TYPE_CODE(+)
  AND C.COMMON_CODE = NUT.COMMON_CODE(+)
  AND NUT.NUT_INFO_CODE = NUTI.NUT_INFO_CODE(+)
  AND C.COMMON_CODE = TR.COMMON_CODE(+)
  AND TR.TRAIN_TYPE = TRT.TRAIN_TYPE_CODE(+)
  AND C.COMMON_CODE = ETC.COMMON_CODE(+)
  AND C.COMMON_CODE = TOI.COMMON_CODE(+)
  AND TOI.URINE_CODE = UR.URINE_CODE(+)
  AND TOI.FECES_CODE = FC.FECES_CODE(+)
  AND C.COMMON_CODE = MED.COMMON_CODE(+)
  AND MED.MEDICINE_INFO_CODE = MEDI.MEDICINE_INFO_CODE(+)
  AND C.COMMON_CODE = BR.COMMON_CODE(+)
ORDER BY COMMON_CODE;
--==>> View DIARYVIEW이(가) 생성되었습니다.

SELECT *
FROM DIARYVIEW
WHERE DAILY_DATE = TO_CHAR(TO_DATE('2021-06-30'), 'YYYY-MM-DD')
  AND RELATION_CODE = 'REL005';

SELECT *
FROM DIARYVIEW
WHERE DAILY_DATE = TO_CHAR(TO_DATE('2021-06-30'), 'YYYY-MM-DD')
  AND RELATION_CODE = 'REL006';


