-- 접속 계정 확인
SELECT USER
FROM DUAL;
--==>> HAROOT

-- 생성된 테이블 리스트 확인
SELECT *
FROM TAB;

-- 세션 설정
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-- 01. TBL_ADMIN : 관리자
CREATE TABLE TBL_ADMIN
( ADMIN_CODE     VARCHAR2(30)
, ADMIN_ID       VARCHAR2(50) NOT NULL 
, ADMIN_PW       VARCHAR2(30) NOT NULL 
, ADMIN_NAME     VARCHAR2(30) NOT NULL
, ADMIN_REGDATE  DATE         DEFAULT SYSDATE
, CONSTRAINT ADMIN_CODE_PK PRIMARY KEY(ADMIN_CODE)
, CONSTRAINT ADMIN_ID_UK UNIQUE(ADMIN_ID)
);
--==>> Table TBL_ADMIN이(가) 생성되었습니다.

DESC TBL_ADMIN;
--==>>
/*
이름            널?       유형           
------------- -------- ------------ 
ADMIN_CODE    NOT NULL VARCHAR2(30) 
ADMIN_ID      NOT NULL VARCHAR2(50) 
ADMIN_PW      NOT NULL VARCHAR2(30) 
ADMIN_NAME    NOT NULL VARCHAR2(30) 
ADMIN_REGDATE          DATE      
*/

INSERT INTO TBL_ADMIN(ADMIN_CODE, ADMIN_ID, ADMIN_PW, ADMIN_NAME)
VALUES ('ADMIN001', 'admin1', CRYPTPACK.ENCRYPT('0308', 'admin1'), '김아별');
INSERT INTO TBL_ADMIN(ADMIN_CODE, ADMIN_ID, ADMIN_PW, ADMIN_NAME)
VALUES ('ADMIN002', 'admin2', CRYPTPACK.ENCRYPT('0909', 'admin2'), '박나현');
--==>> 1 행 이(가) 삽입되었습니다. * 2

SELECT *
FROM TBL_ADMIN;
--==>> 
/*
ADMIN_CODE	ADMIN_ID	ADMIN_PW	ADMIN_NAME	ADMIN_REGDATE
ADMIN001	admin1	    œ��	        김아별	    2021-06-27 15:41:27
ADMIN002	admin2	   �nȣ	        박나현	    2021-06-27 15:44:11
*/


-- 02. TBL_NOTICE_LEG : 공지 카테고리 범례
CREATE TABLE TBL_NOTICE_LEG
( NOTICE_CATE_CODE      VARCHAR2(2)
, NOTICE_CATE_CONTENT   VARCHAR2(30) NOT NULL
, CONSTRAINT NOTICELEG_CODE_PK PRIMARY KEY(NOTICE_CATE_CODE)
);
--==>> Table TBL_NOTICE_LEG이(가) 생성되었습니다.

DESC TBL_NOTICE_LEG;
--==>>
/*
이름                  널?       유형           
------------------- -------- ------------ 
NOTICE_CATE_CODE    NOT NULL VARCHAR2(2)  
NOTICE_CATE_CONTENT NOT NULL VARCHAR2(30) 
*/

INSERT INTO TBL_NOTICE_LEG(NOTICE_CATE_CODE, NOTICE_CATE_CONTENT)
VALUES ('1', '안내');
INSERT INTO TBL_NOTICE_LEG(NOTICE_CATE_CODE, NOTICE_CATE_CONTENT)
VALUES ('2', '필독');
INSERT INTO TBL_NOTICE_LEG(NOTICE_CATE_CODE, NOTICE_CATE_CONTENT)
VALUES ('3', '공지');
--==>> 1 행 이(가) 삽입되었습니다. * 3

SELECT *
FROM TBL_NOTICE_LEG;
--==>>
/*
NOTICE_CATE_CODE	NOTICE_CATE_CONTENT
1	                안내
2	                필독
3	                공지
*/


-- 03. TBL_BOARD_LEG : 게시글 카테고리 범례
CREATE TABLE TBL_BOARD_LEG
( BOARD_CATE_CODE       VARCHAR2(2)
, BOARD_CATE_CONTENT    VARCHAR2(30) NOT NULL
, CONSTRAINT BOARDLEG_CODE_PK PRIMARY KEY(BOARD_CATE_CODE)
);
--==>> Table TBL_BOARD_LEG이(가) 생성되었습니다.

DESC TBL_BOARD_LEG;
--==>>
/*
이름                 널?       유형           
------------------ -------- ------------ 
BOARD_CATE_CODE    NOT NULL VARCHAR2(2)  
BOARD_CATE_CONTENT NOT NULL VARCHAR2(30)
*/

INSERT INTO TBL_BOARD_LEG(BOARD_CATE_CODE, BOARD_CATE_CONTENT)
VALUES ('1', '행사/할인정보');
INSERT INTO TBL_BOARD_LEG(BOARD_CATE_CODE, BOARD_CATE_CONTENT)
VALUES ('2', '리뷰');
INSERT INTO TBL_BOARD_LEG(BOARD_CATE_CODE, BOARD_CATE_CONTENT)
VALUES ('3', '수다');
INSERT INTO TBL_BOARD_LEG(BOARD_CATE_CODE, BOARD_CATE_CONTENT)
VALUES ('4', '중고장터');
--==>> 1 행 이(가) 삽입되었습니다. * 4

SELECT *
FROM TBL_BOARD_LEG;
--==>>
/*
BOARD_CATE_CODE	BOARD_CATE_CONTENT
1	            행사/할인정보
2	            리뷰
3	            수다
4	            중고장터
*/


-- 04. TBL_REPORT_STATE :  신고 처리상태 범례
CREATE TABLE TBL_REPORT_STATE
( REP_STATE_CODE    VARCHAR2(2)
, REP_STATE_CONTENT VARCHAR2(30) NOT NULL
, CONSTRAINT REPSTATE_CODE_PK PRIMARY KEY(REP_STATE_CODE)
);
--==>> Table TBL_REPORT_STATE이(가) 생성되었습니다.

DESC TBL_REPORT_STATE;
--==>>
/*
이름                널?       유형           
----------------- -------- ------------ 
REP_STATE_CODE    NOT NULL VARCHAR2(2)  
REP_STATE_CONTENT NOT NULL VARCHAR2(30)
*/

INSERT INTO TBL_REPORT_STATE(REP_STATE_CODE, REP_STATE_CONTENT)
VALUES ('1', '미처리');
INSERT INTO TBL_REPORT_STATE(REP_STATE_CODE, REP_STATE_CONTENT)
VALUES ('2', '신고해제');
INSERT INTO TBL_REPORT_STATE(REP_STATE_CODE, REP_STATE_CONTENT)
VALUES ('3', '신고확정');
--==>> 1 행 이(가) 삽입되었습니다. * 3

SELECT *
FROM TBL_REPORT_STATE;
--==>>
/*
REP_STATE_CODE	REP_STATE_CONTENT
1	            미처리
2	            신고해제
3	            신고확정
*/


-- 05. TBL_MEMBER : 회원정보
CREATE TABLE TBL_MEMBER
( MEM_CODE      VARCHAR2(30)
, MEM_ID        VARCHAR2(50)    NOT NULL
, MEM_PW        VARCHAR2(30)    NOT NULL
, MEM_NAME      VARCHAR2(30)    NOT NULL
, MEM_BIRTH     DATE            NOT NULL
, MEM_GENDER    VARCHAR2(1)     NOT NULL
, MEM_TEL       VARCHAR2(40)    NOT NULL
, MEM_ADDR      VARCHAR2(200)   NOT NULL
, MEM_REGDATE   DATE            DEFAULT SYSDATE
, MEM_NICKNAME  VARCHAR2(20)    NOT NULL
, CONSTRAINT MEMBER_CODE_PK PRIMARY KEY(MEM_CODE)
, CONSTRAINT MEMBER_ID_UK UNIQUE(MEM_ID)
, CONSTRAINT MEMBER_NICKNAME_UK UNIQUE(MEM_NICKNAME)
);
--==>> Table TBL_MEMBER이(가) 생성되었습니다.

DESC TBL_MEMBER;
--==>>
/*
이름           널?       유형            
------------ -------- ------------- 
MEM_CODE     NOT NULL VARCHAR2(30)  
MEM_ID       NOT NULL VARCHAR2(50)  
MEM_PW       NOT NULL VARCHAR2(30)  
MEM_NAME     NOT NULL VARCHAR2(30)  
MEM_BIRTH    NOT NULL DATE          
MEM_GENDER   NOT NULL VARCHAR2(1)   
MEM_TEL      NOT NULL VARCHAR2(40)  
MEM_ADDR     NOT NULL VARCHAR2(200) 
MEM_REGDATE           DATE          
MEM_NICKNAME NOT NULL VARCHAR2(20)
*/

-- 데이터 입력
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM001', 'joohee', CRYPTPACK.ENCRYPT('1224', 'joohee'), '정주희', TO_DATE('1997-12-24', 'YYYY-MM-DD'), 'F'
, '010-1111-1111', '경기도 광명시 철산동', TO_DATE('2021-05-24', 'YYYY-MM-DD'), '주리짱');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM002', 'hyeyeon', CRYPTPACK.ENCRYPT('1102', 'hyeyeon'), '선혜연', TO_DATE('1995-11-02', 'YYYY-MM-DD'), 'F'
, '010-2222-2222', '경기도 고양시 일산서구 주엽로98', TO_DATE('2021-06-20', 'YYYY-MM-DD'), '사공혜연');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM003', 'harim', CRYPTPACK.ENCRYPT('1022', 'harim'), '이하림', TO_DATE('1997-10-22', 'YYYY-MM-DD'), 'F'
, '010-3333-3333', '서울 금천구 가산동', TO_DATE('2021-06-01', 'YYYY-MM-DD'), '뚜또집사');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM004', 'hojin', CRYPTPACK.ENCRYPT('0302', 'hojin'), '김호진', TO_DATE('1975-03-02', 'YYYY-MM-DD'), 'M'
, '010-4444-4444', '경기도 광명시 철산동', TO_DATE('2021-05-24', 'YYYY-MM-DD'), '나는야호진이');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM005', 'iu', CRYPTPACK.ENCRYPT('0516', 'iu'), '이지은', TO_DATE('1993-05-16', 'YYYY-MM-DD'), 'F'
, '010-5555-5555', '서울 마포구 공덕동', TO_DATE('2021-05-31', 'YYYY-MM-DD'), '이유짱');
--==>> 1 행 이(가) 삽입되었습니다. * 5

-- 닉네임 컬럼 타입 변경 VARCHAR2(20) -> VARCHAR2(50)
ALTER TABLE TBL_MEMBER MODIFY MEM_NICKNAME VARCHAR2(50);

-- 추가 데이터 입력
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM006', 'hyerim', CRYPTPACK.ENCRYPT('1006', 'hyerim'), '이지은', TO_DATE('1997-10-06', 'YYYY-MM-DD'), 'F'
, '010-6666-6666', '경기도 수원시 세류동', TO_DATE('2021-06-19', 'YYYY-MM-DD'), '혜림냥냥');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM007', 'dongwon', CRYPTPACK.ENCRYPT('0118', 'dongwon'), '강동원', TO_DATE('1981-01-18', 'YYYY-MM-DD'), 'M'
, '010-7777-7777', '경상남도 거창군 거창읍', TO_DATE('2021-06-20', 'YYYY-MM-DD'), '맛있는참치');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM008', 'kangjun', CRYPTPACK.ENCRYPT('1012', 'kangjun'), '서강준', TO_DATE('1993-10-12', 'YYYY-MM-DD'), 'M'
, '010-8888-8888', '서울 강남구 자곡동', TO_DATE('2021-06-22', 'YYYY-MM-DD'), '바싹말린강준');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM009', 'moonbin', CRYPTPACK.ENCRYPT('0126', 'moonbin'), '문빈', TO_DATE('1998-01-26', 'YYYY-MM-DD'), 'M'
, '010-9999-9999', '인천 연수구 송도동', TO_DATE('2021-06-23', 'YYYY-MM-DD'), '니가내별이다');
INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, MEM_BIRTH, MEM_GENDER, MEM_TEL, MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
VALUES ('MEM010', 'eunwoo', CRYPTPACK.ENCRYPT('0330', 'eunwoo'), '차은우', TO_DATE('1997-03-30', 'YYYY-MM-DD'), 'M'
, '010-1997-0330', '경기도 군포시 수리산로 37', TO_DATE('2021-06-26', 'YYYY-MM-DD'), '연기연습하는은우');


SELECT MEM_CODE, MEM_ID, MEM_PW, MEM_NAME, TO_CHAR(MEM_BIRTH, 'YYYY-MM-DD') "MEM_BIRTH"
     , MEM_GENDER, MEM_TEL, MEM_ADDR, TO_CHAR(MEM_REGDATE, 'YYYY-MM-DD') "MEM_REGDATE", MEM_NICKNAME
FROM TBL_MEMBER;
--==>>
/*
MEM_CODE	MEM_ID	MEM_PW	MEM_NAME	MEM_BIRTH	MEM_GENDER	MEM_TEL	        MEM_ADDR	                MEM_REGDATE	    MEM_NICKNAME
MEM001	    joohee	"nb��	정주희	    1997-12-24	F	        010-1111-1111	경기도 광명시 철산동	            2021-05-24	    주리짱
MEM002	    hyeyeon	3F&��3F	선혜연	    1995-11-02	F	        010-2222-2222	경기도 고양시 일산서구 주엽로98	    2021-06-20	    사공혜연
MEM003	    harim	-0��_؋�	이하림	    1997-10-22	F	        010-3333-3333	서울 금천구 가산동	            2021-06-01	    뚜또집사
MEM004	    hojin	>Y��	김호진	    1975-03-02	M	        010-4444-4444	경기도 광명시 철산동	            2021-05-24	    나는야호진이
MEM005	    iu	    9Ł��	이지은	    1993-05-16	F	        010-5555-5555	서울 마포구 공덕동	            2021-05-31	    이유짱
*/

-- 06. TBL_SID : 회원 (TBL_MEMBER 참조해옴)
CREATE TABLE TBL_SID
( SID_CODE  VARCHAR2(30)
, MEM_CODE  VARCHAR2(30) NOT NULL
, CONSTRAINT SID_CODE_PK PRIMARY KEY(SID_CODE)
, CONSTRAINT SID_MEMCODE_FK FOREIGN KEY(MEM_CODE)
             REFERENCES TBL_MEMBER(MEM_CODE)
             ON DELETE SET NULL
);
--==>> Table TBL_SID이(가) 생성되었습니다.

-- MEM_CODE NOT NULL 제약사항 제거
--> TBL_MEMBER 에서 삭제되면 NULL 값이 되기 때문에
ALTER TABLE TBL_SID MODIFY MEM_CODE NULL;

DESC TBL_SID;
--==>>
/*
이름       널?       유형           
-------- -------- ------------ 
SID_CODE NOT NULL VARCHAR2(30) 
MEM_CODE NOT NULL VARCHAR2(30) 
*/

-- 데이터 입력
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID001', 'MEM001');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID002', 'MEM002');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID003', 'MEM003');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID004', 'MEM004');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID005', 'MEM005');
--==>> 1 행 이(가) 삽입되었습니다. * 5

-- 추가 데이터 입력
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID006', 'MEM006');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID007', 'MEM007');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID008', 'MEM008');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID009', 'MEM009');
INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
VALUES ('SID010', 'MEM010');
--==>> 1 행 이(가) 삽입되었습니다. * 5

SELECT *
FROM TBL_SID;
--==>>
/*
SID_CODE	MEM_CODE
SID001	    MEM001
SID002	    MEM002
SID003	    MEM003
SID004	    MEM004
SID005	    MEM005
*/

COMMIT;

-- [탈퇴 관련]
--> 탈퇴 시 처리 순서
--> 1. TBL_OUT 에 SID_CODE, OUT_TYPE_CODE 참조해와서 INSERT
--> 2. TBL_SELF_OUT 또는 TBL_BAN 에 회원정보테이블에서 NAME, ID, TEL 가져와서 INSERT
--> 3. TBL_MEMBER 에서 해당 회원 DELETE 

-- 07. TBL_OUT_TYPE : 탈퇴 유형
CREATE TABLE TBL_OUT_TYPE
( OUT_TYPE_CODE     VARCHAR2(2)
, OUT_TYPE_CONTENT  VARCHAR2(30) NOT NULL
, CONSTRAINT OUTTYPE_CODE_PK PRIMARY KEY(OUT_TYPE_CODE)
);
--==>> Table TBL_OUT_TYPE이(가) 생성되었습니다.

DESC TBL_OUT_TYPE;
--==>>
/*
이름               널?       유형           
---------------- -------- ------------ 
OUT_TYPE_CODE    NOT NULL VARCHAR2(2)  
OUT_TYPE_CONTENT NOT NULL VARCHAR2(30)  
*/

INSERT INTO TBL_OUT_TYPE(OUT_TYPE_CODE, OUT_TYPE_CONTENT)
VALUES ('1', '자진탈퇴');
INSERT INTO TBL_OUT_TYPE(OUT_TYPE_CODE, OUT_TYPE_CONTENT)
VALUES ('2', '강제탈퇴');
--==>> 1 행 이(가) 삽입되었습니다. * 2

SELECT *
FROM TBL_OUT_TYPE;
--==>>
/*
OUT_TYPE_CODE	OUT_TYPE_CONTENT
1	            자진탈퇴
2	            강제탈퇴
*/

-- 08. TBL_OUT : 회원 탈퇴
CREATE TABLE TBL_OUT
( OUT_CODE      VARCHAR2(30)
, SID_CODE      VARCHAR2(30) NOT NULL
, OUT_TYPE_CODE VARCHAR2(30) NOT NULL
, OUT_DATE      DATE         DEFAULT SYSDATE
, CONSTRAINT OUT_CODE_PK PRIMARY KEY(OUT_CODE)
, CONSTRAINT OUT_SIDCODE_FK FOREIGN KEY(SID_CODE)
             REFERENCES TBL_SID(SID_CODE)
, CONSTRAINT OUT_TYPECODE_FK FOREIGN KEY(OUT_TYPE_CODE)
             REFERENCES TBL_OUT_TYPE(OUT_TYPE_CODE)
);
--==>> Table TBL_OUT이(가) 생성되었습니다.

DESC TBL_OUT;
--==>>
/*
이름            널?       유형           
------------- -------- ------------ 
OUT_CODE      NOT NULL VARCHAR2(30) 
SID_CODE      NOT NULL VARCHAR2(30) 
OUT_TYPE_CODE NOT NULL VARCHAR2(30) 
OUT_DATE               DATE     
*/


-- 09. TBL_SELF_OUT : 자진탈퇴 체크
CREATE TABLE TBL_SELF_OUT
( SELF_OUT_CODE    VARCHAR2(30)
, SELF_OUT_ID      VARCHAR2(50) NOT NULL
, CONSTRAINT SELFOUT_CODE_PK PRIMARY KEY(SELF_OUT_CODE)
, CONSTRAINT SELFOUT_ID_UK UNIQUE(SELF_OUT_ID)
);
--==>> Table TBL_SELF_OUT이(가) 생성되었습니다.

DESC TBL_SELF_OUT;
--==>>
/*
이름            널?       유형           
------------- -------- ------------ 
SELF_OUT_CODE NOT NULL VARCHAR2(30) 
SELF_OUT_ID   NOT NULL VARCHAR2(50)
*/


-- 10. TBL_BAN : 강제탈퇴체크
CREATE TABLE TBL_BAN
( BAN_CODE  VARCHAR2(30)
, BAN_NAME  VARCHAR2(30) NOT NULL
, BAN_ID    VARCHAR2(50) NOT NULL
, BAN_TEL   VARCHAR2(40) NOT NULL
, CONSTRAINT BAN_CODE_PK PRIMARY KEY(BAN_CODE)
);
--==>> Table TBL_BAN이(가) 생성되었습니다.

DESC TBL_BAN;
--==>>
/*
이름       널?       유형           
-------- -------- ------------ 
BAN_CODE NOT NULL VARCHAR2(30) 
BAN_NAME NOT NULL VARCHAR2(30) 
BAN_ID   NOT NULL VARCHAR2(50) 
BAN_TEL  NOT NULL VARCHAR2(40) 
*/

-- 탈퇴한 회원 데이터 삽입
-- [강제 탈퇴]
-- 탈퇴 테이블에 SID_CODE, OUT_TYPE_CODE 참조해서 데이터 INSERT
INSERT INTO TBL_OUT(OUT_CODE, SID_CODE, OUT_TYPE_CODE)
VALUES ('OUT001', 'SID004', '2');
--==>> 1 행 이(가) 삽입되었습니다.
SELECT *
FROM TBL_OUT;
--==>> OUT001	SID004	2	2021-06-28 00:06:42

-- 강제 탈퇴 테이블에 이름, 아이디, 전화번호 INSERT
INSERT INTO TBL_BAN(BAN_CODE, BAN_NAME, BAN_ID, BAN_TEL)
VALUES ('BAN001', '김호진', 'hojin', '010-4444-4444');
--==>> 1 행 이(가) 삽입되었습니다.
SELECT *
FROM TBL_BAN;
--==>> BAN001	김호진	hojin	010-4444-4444

-- 회원 정보 테이블에서 해당 회원 DELETE
DELETE
FROM TBL_MEMBER
WHERE MEM_CODE = 'MEM004';
--==>> 1 행 이(가) 삭제되었습니다.
SELECT *
FROM TBL_MEMBER;
--==>>
/*
MEM_CODE	MEM_ID	MEM_PW	MEM_NAME	MEM_BIRTH	MEM_GENDER	MEM_TEL	        MEM_ADDR	            MEM_REGDATE	MEM_NICKNAME
MEM001	    joohee	"nb��	정주희	    1997-12-24	F	        010-1111-1111	경기도 광명시 철산동	        2021-05-24 	주리짱
MEM002	    hyeyeon	3F&��3F	선혜연	    1995-11-02	F	        010-2222-2222	경기도 고양시 일산서구 주엽로98	2021-06-20  사공혜연
MEM003	    harim	-0��_؋�	이하림	    1997-10-22 	F	        010-3333-3333	서울 금천구 가산동	        2021-06-01  뚜또집사
MEM005	    iu	    9Ł��	이지은	    1993-05-16	F	        010-5555-5555	서울 마포구 공덕동	        2021-05-31  이유짱
*/
SELECT *
FROM TBL_SID;
--==>>
/*
SID001	MEM001
SID002	MEM002
SID003	MEM003
SID004	(null)
SID005	MEM005
*/

-- [자진 탈퇴]
-- 탈퇴 테이블 SID_CODE, OUT_TYPE_CODE 참조해서 데이터 INSERT
INSERT INTO TBL_OUT(OUT_CODE, SID_CODE, OUT_TYPE_CODE)
VALUES ('OUT002', 'SID005', '1');
--==>> 1 행 이(가) 삽입되었습니다.
SELECT *
FROM TBL_OUT;
--==>>
/*
OUT001	SID004	2	2021-06-28 00:06:42
OUT002	SID005	1	2021-06-28 00:54:24
*/

-- 자진 탈퇴 테이블에 이름, 아이디, 전화번호 INSERT
INSERT INTO TBL_SELF_OUT(SELF_OUT_CODE, SELF_OUT_ID)
VALUES ('SEL001', 'iu');
--==>> 1 행 이(가) 삽입되었습니다.

-- 회원 정보 테이블에서 해당 회원 DELETE
DELETE
FROM TBL_MEMBER
WHERE MEM_CODE='MEM005';
--==>> 1 행 이(가) 삽입되었습니다.


-- 11. TBL_FAQ : 자주하는 질문
CREATE TABLE TBL_FAQ
( FAQ_CODE      VARCHAR2(30)
, FAQ_TITLE     VARCHAR2(100) NOT NULL
, FAQ_CONTENT   VARCHAR2(4000) NOT NULL
, CONSTRAINT FAQ_CODE_PK PRIMARY KEY(FAQ_CODE)
);
--==>> Table TBL_FAQ이(가) 생성되었습니다.

DESC TBL_FAQ;
--==>>
/*
이름          널?       유형             
----------- -------- -------------- 
FAQ_CODE    NOT NULL VARCHAR2(30)   
FAQ_TITLE   NOT NULL VARCHAR2(100)  
FAQ_CONTENT NOT NULL VARCHAR2(4000) 
*/


-- 12. TBL_ASK_LEG : 문의 카테고리
CREATE TABLE TBL_ASK_LEG
( ASK_CATE_CODE     VARCHAR2(30)
, ASK_CATE_CONTENT  VARCHAR2(30) NOT NULL
, CONSTRAINT ASKLEG_CODE_PK PRIMARY KEY(ASK_CATE_CODE)
);
--==>> Table TBL_ASK_LEG이(가) 생성되었습니다.

DESC TBL_ASK_LEG;
--==>>
/*
이름               널?       유형           
---------------- -------- ------------ 
ASK_CATE_CODE    NOT NULL VARCHAR2(30) 
ASK_CATE_CONTENT NOT NULL VARCHAR2(30) 
*/

INSERT INTO TBL_ASK_LEG(ASK_CATE_CODE, ASK_CATE_CONTENT)
VALUES ('1', '산책메이트');
INSERT INTO TBL_ASK_LEG(ASK_CATE_CODE, ASK_CATE_CONTENT)
VALUES ('2', '다이어리');
INSERT INTO TBL_ASK_LEG(ASK_CATE_CODE, ASK_CATE_CONTENT)
VALUES ('3', '게시판');
INSERT INTO TBL_ASK_LEG(ASK_CATE_CODE, ASK_CATE_CONTENT)
VALUES ('4', '계정');
INSERT INTO TBL_ASK_LEG(ASK_CATE_CODE, ASK_CATE_CONTENT)
VALUES ('5', '기타');
--==>> 1 행 이(가) 삽입되었습니다. * 5

-- 13. TBL_ASK_STATE : 문의처리상태
CREATE TABLE TBL_ASK_STATE
( ASK_STATE_CODE    VARCHAR2(2)
, ASK_STATE_CONTENT VARCHAR2(30) NOT NULL
, CONSTRAINT ASKSTATE_CODE_PK PRIMARY KEY(ASK_STATE_CODE)
);
--==>> Table TBL_ASK_STATE이(가) 생성되었습니다.

ALTER TABLE TBL_ASK_STATE MODIFY ASK_STATE_CONTENT VARCHAR2(30);

INSERT INTO TBL_ASK_STATE(ASK_STATE_CODE, ASK_STATE_CONTENT)
VALUES ('1', '미처리');
INSERT INTO TBL_ASK_STATE(ASK_STATE_CODE, ASK_STATE_CONTENT)
VALUES ('2', '답변완료');
--==>> 1 행 이(가) 삽입되었습니다. * 2

SELECT *
FROM TBL_ASK_STATE;
--==>> 
/*
1	미처리
2	답변완료
*/

COMMIT;
--==>> 커밋 완료.


-- 14. TBL_REWARD : 상벌점
CREATE TABLE TBL_REWARD
( REWARD_CODE    VARCHAR2(2)
, REWARD_SCORE   NUMBER(3) NOT NULL
, REWARD_CONTENT VARCHAR2(100) NOT NULL
, CONSTRAINT REWARD_CODE_PK PRIMARY KEY(REWARD_CODE)
);
--==>> Table TBL_REWARD이(가) 생성되었습니다.

