--○ PRC_MEMBER_INSERT
CREATE OR REPLACE PROCEDURE PRC_MEMBER_INSERT
( V_MEM_ID              IN TBL_MEMBER.MEM_ID%TYPE
, V_MEM_PW              IN TBL_MEMBER.MEM_PW%TYPE
, V_MEM_NAME            IN TBL_MEMBER.MEM_NAME%TYPE
, V_MEM_BIRTH           IN TBL_MEMBER.MEM_BIRTH%TYPE
, V_MEM_GENDER          IN TBL_MEMBER.MEM_GENDER%TYPE
, V_MEM_TEL             IN TBL_MEMBER.MEM_TEL%TYPE
, V_MEM_ADDR            IN TBL_MEMBER.MEM_ADDR%TYPE
, V_MEM_NICKNAME        IN TBL_MEMBER.MEM_NICKNAME%TYPE
, V_WALK_AGREE_CHECK    IN TBL_WALK_AGREE.WALK_AGREE_CHECK%TYPE
)
IS
    V_MEM_CODE            TBL_MEMBER.MEM_CODE%TYPE;
    V_SID_CODE            TBL_SID.SID_CODE%TYPE;
    V_WALK_AGREE_CODE     TBL_WALK_AGREE.WALK_AGREE_CODE%TYPE;
    USER_DEFINE_ERROR   EXCEPTION;
    
BEGIN
    -- MEM_CODE 자동입력
    SELECT CONCAT('MEM', NVL(MAX(TO_NUMBER(SUBSTR(MEM_CODE, 4))), 0) + 1) INTO V_MEM_CODE
    FROM TBL_MEMBER;
    
    -- INSERT MEMBER 쿼리문
    INSERT INTO TBL_MEMBER(MEM_CODE, MEM_ID, MEM_PW, MEM_NAME
    , MEM_BIRTH, MEM_GENDER, MEM_TEL
    , MEM_ADDR, MEM_REGDATE, MEM_NICKNAME)
    VALUES (V_MEM_CODE, V_MEM_ID, CRYPTPACK.ENCRYPT(V_MEM_PW, V_MEM_ID), V_MEM_NAME
    , TO_DATE(V_MEM_BIRTH, 'YYYY-MM-DD'),  V_MEM_GENDER
    , (SUBSTR(V_MEM_TEL, 1, 3) || '-' || SUBSTR(V_MEM_TEL, 5, 4) || '-' || SUBSTR(V_MEM_TEL, 10, 12))
    , V_MEM_ADDR
    , TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS')
    , V_MEM_NICKNAME);
    
    
     -- SID_CODE 자동입력
    SELECT CONCAT('SID', NVL(MAX(TO_NUMBER(SUBSTR(SID_CODE, 4))),0) + 1) INTO V_SID_CODE
    FROM TBL_SID;   
    
    -- INSERT SID 쿼리문
    INSERT INTO TBL_SID(SID_CODE, MEM_CODE)
    VALUES(V_SID_CODE, V_MEM_CODE);
    
    
     -- WALK_AGREE_CODE 자동입력
    SELECT CONCAT('AGR', NVL(MAX(TO_NUMBER(SUBSTR(WALK_AGREE_CODE, 4, 6))), 0) + 1) INTO V_WALK_AGREE_CODE
    FROM TBL_WALK_AGREE;   
    
    -- INSERT WALK_AGREE 쿼리문
    INSERT INTO TBL_WALK_AGREE(WALK_AGREE_CODE, SID_CODE, WALK_AGREE_CHECK, WALK_AGREE_DATE)
    VALUES(V_WALK_AGREE_CODE, V_SID_CODE, V_WALK_AGREE_CHECK
    , TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS'));
        
    
END;

EXEC PRC_MEMBER_INSERT('amugona', '1231', '박지혜', '1990-02-31', 'F', '010-2315-7634', '서울 강동구 천호동', '지혜로워', 'Y');

SELECT *
FROM TBL_MEMBER
ORDER BY MEM_CODE;


UPDATE TBL_MEMBER
SET MEM_TEL='010-1213-7687'
WHERE MEM_CODE='MEM13';



SELECT SUBSTR(MEM_TEL, 1, 3) 
FROM TBL_MEMBER;

SELECT SUBSTR(MEM_TEL, 5, 4) 
FROM TBL_MEMBER;

SELECT SUBSTR(MEM_TEL, 10, 12)
FROM TBL_MEMBER;





----반려동물 등록(PET ADD 프로시저)

CREATE OR REPLACE PROCEDURE PRC_PET_INSERT
( V_PET_PHOTO               IN TBL_PET_INFO.PET_PHOTO%TYPE     
, V_PET_NAME                IN TBL_PET_INFO.PET_NAME%TYPE
, V_PET_SEX                 IN TBL_PET.PET_SEX%TYPE
, V_DESEX_CONTENT           IN TBL_DESEX_LEG.DESEX_CONTENT%TYPE
, V_INJECT_TYPE_NAME        IN TBL_INJECT_TYPE.INJECT_TYPE_NAME%TYPE
, V_PET_TYPE_NAME           IN TBL_PET_TYPE.PET_TYPE_NAME%TYPE
, V_PET_BIRTH               IN TBL_PET.PET_BIRTH%TYPE
, V_PET_ADDR                IN TBL_PET_INFO.PET_ADDR%TYPE
, V_PET_ADDR_LAT            IN TBL_PET_INFO.PET_ADDR_LAT%TYPE
, V_PET_ADDR_LNG            IN TBL_PET_INFO.PET_ADDR_LNG%TYPE
, V_PET_FAV_PLACE           IN TBL_PET.PET_FAV_PLACE%TYPE
, V_PET_FAV_LAT             IN TBL_PET.PET_FAV_LAT%TYPE
, V_PET_FAV_LNG             IN TBL_PET.PET_FAV_LNG%TYPE
, V_PET_REGNUM              IN TBL_PET_INFO.PET_REGNUM%TYPE
, V_DISEASE_CONTENT         IN TBL_DISEASE_TYPE.DISEASE_CONTENT%TYPE
, V_FAV_FOOD_CONTENT        IN TBL_FAV_FOOD_TYPE.FAV_FOOD_CONTENT%TYPE
, V_PET_SOCIAL              IN VARCHAR2
, V_PET_CHAR1_CONTENT       IN TBL_PET_CHAR1.PET_CHAR1_CONTENT%TYPE
, V_PET_CHAR2_CONTENT       IN TBL_PET_CHAR2.PET_CHAR2_CONTENT%TYPE
, V_PET_CHAR3_CONTENT       IN TBL_PET_CHAR3.PET_CHAR3_CONTENT%TYPE    
, V_PET_CHAR4_CONTENT       IN TBL_PET_CHAR4.PET_CHAR4_CONTENT%TYPE
, V_BITE_CONTENT            IN TBL_BITE_LEG.BITE_CONTENT%TYPE
, V_RELATION_TYPE_CONTENT   IN TBL_RELATION_TYPE.RELATION_TYPE_CONTENT%TYPE
, V_SID_CODE                IN TBL_SID.SID_CODE%TYPE
)
IS
    V_PET_CODE              TBL_PET.PET_CODE%TYPE;                  -- 자동 생성
    V_PET_INFO_CODE         TBL_PET_INFO.PET_INFO_CODE%TYPE;             -- 자동 생성
    V_DESEX_CODE            TBL_DESEX_LEG.DESEX_CODE%TYPE;          -- 범례
    V_VACCINE_CODE          TBL_VACCINE.VACCINE_CODE%TYPE;          -- 자동 생성
    V_INJECT_TYPE_CODE      TBL_INJECT_TYPE.INJECT_TYPE_CODE%TYPE;
    V_PET_TYPE_CODE         TBL_PET_TYPE.PET_TYPE_CODE%TYPE;        -- 범례
    V_PET_TYPE_SIZE         TBL_PET_TYPE.PET_TYPE_SIZE%TYPE;
    V_DISEASE_CODE          TBL_DISEASE.DISEASE_CODE%TYPE;          -- 자동 생성
    V_DISEASE_TYPE_CODE     TBL_DISEASE_TYPE.DISEASE_TYPE_CODE%TYPE; 
    V_FAV_FOOD_CODE         TBL_FAV_FOOD.FAV_FOOD_CODE%TYPE;        -- 자동 생성
    V_FAV_FOOD_TYPE_CODE    TBL_FAV_FOOD_TYPE.FAV_FOOD_TYPE_CODE%TYPE;
    V_PET_CHAR1_CODE        TBL_PET_CHAR1.PET_CHAR1_CODE%TYPE;      -- 범례
    V_PET_CHAR2_CODE        TBL_PET_CHAR2.PET_CHAR2_CODE%TYPE;      -- 범례
    V_PET_CHAR3_CODE        TBL_PET_CHAR3.PET_CHAR3_CODE%TYPE;      -- 범례
    V_PET_CHAR4_CODE        TBL_PET_CHAR4.PET_CHAR4_CODE%TYPE;      -- 범례
    V_BITE_CODE             TBL_BITE_LEG.BITE_CODE%TYPE;            -- 범례
    V_RELATION_CODE         TBL_RELATION.RELATION_CODE%TYPE;       -- 자동 생성
    V_RELATION_TYPE_CODE    TBL_RELATION_TYPE.RELATION_TYPE_CODE%TYPE;   
BEGIN
    -- V_PET_CODE
    SELECT CONCAT('PET', NVL(MAX(TO_NUMBER(SUBSTR(PET_CODE, 4))), 0) + 1) INTO V_PET_CODE
    FROM TBL_PET;    
    
    -- V_PET_INFO_CODE
    SELECT CONCAT('PETIN', NVL(MAX(TO_NUMBER(SUBSTR(PET_INFO_CODE, 6))), 0) + 1) INTO V_PET_INFO_CODE
    FROM TBL_PET_INFO; 
    
    -- V_DESEX_CODE
    SELECT DESEX_CODE INTO V_DESEX_CODE
    FROM TBL_DESEX_LEG
    WHERE DESEX_CONTENT=V_DESEX_CONTENT;
    
    -- V_INJECT_TYPE_CODE
    SELECT INJECT_TYPE_CODE INTO V_INJECT_TYPE_CODE
    FROM TBL_INJECT_TYPE;
    
    -- V_VACCINE_CODE
    SELECT CONCAT('VAC', NVL(MAX(TO_NUMBER(SUBSTR(VACCINE_CODE, 4))), 0) + 1) INTO V_VACCINE_CODE
    FROM TBL_VACCINE;    
    
    -- V_PET_TYPE_CODE, V_PET_TYPE_SIZE  
    SELECT PET_TYPE_CODE INTO V_PET_TYPE_CODE
    FROM TBL_PET_TYPE
    WHERE PET_TYPE_NAME = V_PET_TYPE_NAME;
    
    SELECT PET_TYPE_SIZE INTO V_PET_TYPE_SIZE
    FROM TBL_PET_TYPE
    WHERE PET_TYPE_NAME = V_PET_TYPE_NAME;
    
    -- V_DISEASE_CODE
    SELECT CONCAT('DIS', NVL(MAX(TO_NUMBER(SUBSTR(DISEASE_CODE, 4))), 0) + 1) INTO V_DISEASE_CODE
    FROM TBL_DISEASE;
    
    -- V_DISEASE_TYPE_CODE  
    SELECT DISEASE_TYPE_CODE INTO V_DISEASE_TYPE_CODE
    FROM TBL_DISEASE_TYPE
    WHERE DISEASE_CONTENT=V_DISEASE_CONTENT;
    
    -- V_FAV_FOOD
    SELECT CONCAT('FAVF', NVL(MAX(TO_NUMBER(SUBSTR(FAV_FOOD_CODE, 5))), 0) + 1) INTO V_FAV_FOOD_CODE
    FROM TBL_FAV_FOOD;   
    
    -- V_FAV_FOOD_TYPE_CODE 
    SELECT FAV_FOOD_TYPE_CODE INTO V_FAV_FOOD_TYPE_CODE
    FROM TBL_FAV_FOOD_TYPE
    WHERE FAV_FOOD_CONTENT = V_FAV_FOOD_CONTENT;
    
    -- V_PET_CHAR1_CODE 
    SELECT PET_CHAR1_CODE INTO V_PET_CHAR1_CODE
    FROM TBL_PET_CHAR1
    WHERE PET_CHAR1_CONTENT = V_PET_CHAR1_CONTENT;
    
    -- V_PET_CHAR2_CODE 
    SELECT PET_CHAR2_CODE INTO V_PET_CHAR2_CODE
    FROM TBL_PET_CHAR2
    WHERE PET_CHAR2_CONTENT = V_PET_CHAR2_CONTENT;
    
    -- V_PET_CHAR3_CODE 
    SELECT PET_CHAR3_CODE INTO V_PET_CHAR3_CODE
    FROM TBL_PET_CHAR3
    WHERE PET_CHAR3_CONTENT = V_PET_CHAR3_CONTENT;
    
    -- V_PET_CHAR4_CODE  
    SELECT PET_CHAR4_CODE INTO V_PET_CHAR4_CODE
    FROM TBL_PET_CHAR4
    WHERE PET_CHAR4_CONTENT = V_PET_CHAR4_CONTENT;
    
    -- V_BITE_CODE    
    SELECT BITE_CODE INTO V_BITE_CODE
    FROM TBL_BITE_LEG
    WHERE BITE_CONTENT = V_BITE_CONTENT;
    
    -- V_RELATION_CODE
    SELECT CONCAT('REL', NVL(MAX(TO_NUMBER(SUBSTR(RELATION_CODE, 4))), 0) + 1) INTO V_RELATION_CODE
    FROM TBL_RELATION; 
    
    -- V_RELATION_TYPE_CODE  
    SELECT RELATION_TYPE_CODE INTO V_RELATION_TYPE_CODE
    FROM TBL_RELATION_TYPE
    WHERE RELATION_TYPE_CONTENT = V_RELATION_TYPE_CONTENT;
    
    -- INSERT TBL_PET
    INSERT INTO TBL_PET(PET_CODE, PET_TYPE_CODE, BITE_CODE, DESEX_CODE, PET_SEX, PET_BIRTH
    , PET_FAV_PLACE, PET_SOCIAL, PET_CHAR1_CODE, PET_CHAR2_CODE, PET_CHAR3_CODE, PET_CHAR4_CODE
    , PET_SIZE, PET_FAV_LAT, PET_FAV_LNG)
    VALUES(V_PET_CODE, V_PET_TYPE_CODE, V_BITE_CODE, V_DESEX_CODE, V_PET_SEX, V_PET_BIRTH
    , V_PET_FAV_PLACE, TO_NUMBER(V_PET_SOCIAL), V_PET_CHAR1_CODE, V_PET_CHAR2_CODE, V_PET_CHAR3_CODE, V_PET_CHAR4_CODE
    , V_PET_TYPE_SIZE, V_PET_FAV_LAT, V_PET_FAV_LNG);
    
    -- INSERT TBL_PET_INFO
    INSERT INTO TBL_PET_INFO(PET_INFO_CODE, PET_CODE, PET_NAME, PET_PHOTO,
    PET_ADDR, PET_REGNUM, PET_ADDR_LAT, PET_ADDR_LNG)
    VALUES(V_PET_INFO_CODE, V_PET_CODE, V_PET_NAME, V_PET_PHOTO,
    V_PET_ADDR, V_PET_REGNUM, V_PET_ADDR_LAT, V_PET_ADDR_LNG);
    
    -- INSERT TBL_VACCINE 
    INSERT INTO TBL_VACCINE(VACCINE_CODE, PET_CODE, INJECT_TYPE_CODE)
    VALUES(V_VACCINE_CODE, V_PET_CODE, V_INJECT_TYPE_CODE);
    
    -- INSERT TBL_FAV_FOOD
    INSERT INTO TBL_FAV_FOOD(FAV_FOOD_CODE, PET_CODE, FAV_FOOD_TYPE_CODE)
    VALUES(V_FAV_FOOD_CODE, V_PET_CODE, V_FAV_FOOD_TYPE_CODE);
    
    -- INSERT TBL_DISEASE
    INSERT INTO TBL_DISEASE(DISEASE_CODE, PET_CODE, DISEASE_TYPE_CODE)
    VALUES(V_DISEASE_CODE, V_PET_CODE, V_DISEASE_TYPE_CODE);
    
    -- INSERT TBL_RELATION
    INSERT INTO TBL_RELATION(RELATION_CODE, SID_CODE, PET_CODE, RELATION_TYPE_CODE)
    VALUES(V_RELATION_CODE, V_SID_CODE, V_PET_CODE, V_RELATION_TYPE_CODE);
END;






