SELECT SID,SERIAL#,USERNAME,STATUS FROM V$SESSION WHERE SCHEMANAME='HAROOT';

DROP USER HAROOT CASCADE;

SELECT SID,SERIAL#,USERNAME,STATUS FROM V$SESSION WHERE SCHEMANAME='HTEST';

DROP USER HTEST CASCADE;

COMMIT;